#cloud-config

yum_repos:
  zulu-openjdk:
    name: zulu-openjdk
    baseurl: https://repos.azul.com/zulu/rpm
    type: rpm-md
    skip_if_unavailable: true
    gpgcheck: true
    gpgkey: https://assets.azul.com/files/0xB1998361219BD9C9.txt
    enabled: 1

locale: en_US.UTF-8
timezone: Europe/Lisbon
packages:
  - avahi
  - htop
  - vim
  - curl
  - less
  - wget
  - sudo
  - net-tools
  - restic
  - make
  - sqlite
  - zulu18-jdk-headless

runcmd:
  - echo "DONE"